name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory
        run: ls -R .
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build

  check:
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory
        run: ls -R .
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun check
